set(RAPTORQ_NAME "libraptor")
set(RAPTORQ_EXEC "libraptor")

set(RAPTORQ_VERSION_MAJOR 0)
set(RAPTORQ_VERSION_MINOR 1)
set(RAPTORQ_VERSION_PATCH 0)

set(RAPTORQ_VERSION "${RAPTORQ_VERSION_MAJOR}.${RAPTORQ_VERSION_MINOR}.${RAPTORQ_VERSION_PATCH}")
