#ifndef __RAPTORQ_VERSION_H__
#define __RAPTORQ_VERSION_H__

#define RAPTORQ_VERSION_MAJOR 0
#define RAPTORQ_VERSION_MINOR 1
#define RAPTORQ_VERSION_PATCH 0

#define RAPTORQ_VERSION "0.1.0"

#endif // __RAPTORQ_VERSION_H__
